on:
  push:
    branches:
    - "feat/*"  # Support wildcard matching
    - "fix/*"  # Support wildcard matching
    - "docs/*"  # Support wildcard matching
    - "style/*"  # Support wildcard matching
    - "docs/*"  # Support wildcard matching
    - "refactor/*"  # Support wildcard matching
    - "perf/*"  # Support wildcard matching
    - "test/*"  # Support wildcard matching
    - "build/*"  # Support wildcard matching
    - "ci/*"  # Support wildcard matching
    - "chore/*"  # Support wildcard matching
    - "revert/*"  # Support wildcard matching
jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.1.0
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        source_branch: ""                                 # If blank, default: triggered branch
        destination_branch: "develop"                     # If blank, default: master
        pr_title: "$GITHUB_REF: Pulling into develop"     # Title of pull request
        pr_body: ":crown: *An automated PR*"              # Full markdown support, requires pr_title to be set
        pr_template: ".github/PULL_REQUEST_TEMPLATE.md"   # Path to pull request template, requires pr_title to be set, excludes pr_body
        pr_reviewer: "wei,worker"                         # Comma-separated list (no spaces)
        pr_assignee: "wei,worker"                         # Comma-separated list (no spaces)
        pr_label: $GITHUB_REF                             # Comma-separated list (no spaces)
        pr_draft: true                                    # Creates pull request as draft
        pr_allow_empty: true                              # Creates pull request even if there are no changes
        github_token: ${{ secrets.GITHUB_TOKEN }}